// ცენტრალური თარგმანი — შეცვალე აქ და ორივე ენა (/ და /en) განახლდება.
// Central translation dictionary — edit here, both routes update.
// სტრუქტურა 1:1 ემთხვევა redesign-ის სექციებს (design_handoff_besosurmava_redesign).

export type Lang = "ka" | "en";

export const locales: Record<Lang, { intl: string; cityShort: string }> = {
  ka: { intl: "ka-GE", cityShort: "თბილისი" },
  en: { intl: "en-US", cityShort: "Tbilisi" },
};

export const copy = {
  ka: {
    navCta: "დაკავშირება",
    nav: [
      { label: "მთავარი", href: "#top" },
      { label: "სერვისები", href: "#services" },
      { label: "ნამუშევრები", href: "#work" },
      { label: "ფასები", href: "#pricing" },
      { label: "კონტაქტი", href: "#contact" },
    ],
    hero: {
      eyebrow: "ვებ-სტუდია · ქუთაისი / თბილისი — ხელმისაწვდომი",
      pre: "ვებსაიტები, რომლებიც",
      em: "მუშაობს",
      post: "თქვენი ბიზნესისთვის.",
      sub: "ვაგებ პრემიუმ ვებსაიტებს სასტუმროების, რესტორნებისა და ბრენდებისთვის — სუფთა, სწრაფი, მობილურზე მორგებული და შედეგზე ორიენტირებული.",
      cta1: "დავიწყოთ პროექტი",
      cta2: "ნამუშევრების ნახვა",
      scroll: "გადაახვიეთ",
      stats: [
        { num: "3+", label: "წელი" },
        { num: "12", label: "პროექტი" },
        { num: "24სთ", label: "პასუხი" },
      ],
    },
    services: {
      number: "01",
      kicker: "რას ვაკეთებთ",
      title: "სრული სერვისი — იდეიდან გაშვებამდე",
      intro: "ერთ ადგილას თავს ვუყრით ყველაფერს, რაც თქვენს ბიზნესს ონლაინ წარმატებისთვის სჭირდება.",
      items: [
        { num: "01", icon: "✦", title: "ვებ დიზაინი", body: "თქვენს ბრენდზე მორგებული, თანამედროვე და სუფთა ინტერფეისი — სუფთა ტიპოგრაფიკით, თბილი ფერებით და გააზრებული გრიდით.", tag: "ბრენდინგი · ვიზუალური ენა" },
        { num: "02", icon: "↗", title: "დეველოპმენტი", body: "Next.js-ით აგებული, საიმედო და სწრაფი საიტი, რომელიც წლების განმავლობაში გამართულად მუშაობს.", tag: "Next.js · Performance" },
        { num: "03", icon: "▢", title: "მობილური ვერსია", body: "მთავარი ფოკუსი — ტელეფონის ეკრანი. სტუმრების უმეტესობა საიტს მობილურზე ხსნის.", tag: "Mobile-first" },
        { num: "04", icon: "✧", title: "SEO & სიჩქარე", body: "Google-ში ხილვადობა და ელვისებური ჩატვირთვა — Core Web Vitals 90+, AVIF გამოსახულებები და სუფთა მეტა-ტეგები.", tag: "Core Web Vitals · Schema" },
      ],
    },
    marquee: ["სასტუმროები", "რესტორნები", "კოტეჯები", "ბრენდინგი", "ვებსაიტები", "ქუთაისი"],
    work: {
      number: "02",
      kicker: "ნამუშევრები",
      title: "შერჩეული პროექტები",
      intro: "ცოცხალი საიტები, რომლებიც უკვე მუშაობს და კლიენტებს ემსახურება.",
      note: "ფარული პროექტი? ვაგებ ვებსაიტებს რესტორნებისთვის, კოტეჯებისთვის და მცირე ბრენდებისთვისაც —",
      noteLink: "მომწერეთ",
      items: [
        { num: "01", name: "Georgian House", type: "სასტუმრო · ქუთაისი", desc: "თანამედროვე საიტი ჯავშნებითა და ორი ენით." },
        { num: "02", name: "Kvirike Hills", type: "ბუტიკ-სასტუმრო · კოტეჯები", desc: "სამენოვანი საიტი ცოცხალი ჯავშნებით." },
      ],
    },
    process: {
      number: "03",
      kicker: "პროცესი",
      title: "როგორ ვმუშაობ",
      intro: "მარტივი, გასაგები ნაბიჯები — თქვენგან მხოლოდ ფოტოები და ინფორმაცია მჭირდება.",
      steps: [
        { num: "01", title: "ვეცნობი თქვენს ბიზნესს", body: "მოკლე საუბარი ტელეფონით ან WhatsApp-ით: რა გჭირდებათ, ვინ არიან თქვენი სტუმრები და რა უნდა გააკეთოს საიტმა." },
        { num: "02", title: "გიგზავნით შეთავაზებას", body: "ზუსტი ფასი, ვადა და რას მიიღებთ — ყველაფერი წინასწარ, მოულოდნელობების გარეშე." },
        { num: "03", title: "თქვენ აგზავნით ფოტოებსა და ინფორმაციას", body: "ფოტოები, ფასები, ტექსტები. თუ რამე აკლია, დაგეხმარებით სტრუქტურისა და ტექსტების მომზადებაში." },
        { num: "04", title: "ვაშენებ და გაჩვენებთ", body: "ვაგზავნი სამუშაო ვერსიის ბმულს — ნახულობთ ტელეფონზეც და კომპიუტერზეც, და ერთად ვასწორებთ დეტალებს." },
        { num: "05", title: "საიტი ქვეყნდება", body: "ვაკავშირებ დომენს, ვაქვეყნებ საიტს და გადმოგცემთ ყველაფერს. სურვილისამებრ — შემდგომი მხარდაჭერა." },
      ],
    },
    pricing: {
      number: "04",
      kicker: "ფასები",
      title: "გამჭვირვალე პაკეტები",
      intro: "საბოლოო ფასი დამოკიდებულია პროექტის მოცულობაზე — მომწერეთ და ერთ დღეში მიიღებთ ზუსტ შეთავაზებას.",
      popular: "პოპულარული",
      from: "დან",
      cta: "შეთავაზების მიღება",
      note: "დომენი და ჰოსტინგი ცალკე ღირს (წელიწადში დაახლოებით 40–100₾) — ყველაფერს მე მოგიგვარებთ.",
      tiers: [
        { name: "სავიზიტო გვერდი", price: "600₾", popular: false, desc: "ერთგვერდიანი თანამედროვე საიტი მცირე ბიზნესისთვის, რომელსაც სწრაფად სჭირდება ონლაინ წარმომადგენლობა.", features: ["ერთგვერდიანი დიზაინი", "მობილურზე სრულად მორგებული", "გალერეა და ბიზნესის აღწერა", "კონტაქტი: ზარი, WhatsApp, რუკა", "მზადაა დაახლოებით 1 კვირაში"] },
        { name: "სტანდარტული საიტი", price: "1000₾", popular: true, desc: "სრულფასოვანი ვებსაიტი სასტუმროსთვის, კოტეჯისთვის ან რესტორნისთვის — ყველაზე ხშირად ამას ირჩევენ.", features: ["4–6 გვერდი (ოთახები/მენიუ, გალერეა…)", "ფასები და დეტალური ინფორმაცია", "ჯავშნის / კონტაქტის ფორმა", "ორი ენა (ქართული + ინგლისური)", "საბაზისო SEO ოპტიმიზაცია", "მზადაა დაახლოებით 2 კვირაში"] },
        { name: "პრემიუმ საიტი", price: "1500₾", popular: false, desc: "ყველაფერი სტანდარტული პაკეტიდან და დამატებით — ადმინ პანელი: ფასებსა და ფოტოებს თავად განაახლებთ.", features: ["ყველაფერი სტანდარტული პაკეტიდან", "ადმინ პანელი მართვისთვის", "ჯავშნის შეტყობინებები ელფოსტაზე", "მეტი გვერდი და ფუნქცია საჭიროებისას", "გაშვების შემდეგ მხარდაჭერა"] },
      ],
    },
    faq: {
      number: "05",
      kicker: "გავრცელებული კითხვები",
      title: "რასაც ხშირად მეკითხებიან",
      items: [
        { num: "01", q: "რამდენ ხანში მზადდება საიტი?", a: "სავიზიტო გვერდი — დაახლოებით 1 კვირაში. სტანდარტული საიტი — 2 კვირაში. პრემიუმ პაკეტი — 3–4 კვირაში, რთულობის მიხედვით. ზუსტ ვადას წინასწარ შეთანხმებაში ვწერ." },
        { num: "02", q: "შემიძლია თვითონ განვაახლო კონტენტი?", a: "დიახ — პრემიუმ პაკეტში შედის ადმინ პანელი, საიდანაც ფასებს, ფოტოებსა და ტექსტებს თავად ანახლებთ. სტანდარტული პაკეტისთვის მცირე ცვლილებები ჩემს მხარდაჭერაში შედის." },
        { num: "03", q: "რა ღირს დომენი და ჰოსტინგი?", a: "დომენი — დაახლოებით 40–60₾ წელიწადში. ჰოსტინგი — ჩვეულებრივ უფასოა Vercel-ის გვერდიდან (პოპულარული ვარიანტი) ან 40–80₾ წელიწადში პრემიუმ გადაწყვეტებზე. ყველაფერს თქვენთან ერთად ვაკონფიგურირებ." },
        { num: "04", q: "რა მოხდება საიტის გაშვების შემდეგ?", a: "1 თვის უფასო მხარდაჭერა — ნებისმიერ შეცდომას ვასწორებ ხელფასის გარეშე. ამის შემდეგ — ან თქვენ ანახლებთ თვითონ, ან ვთანამშრომლობთ ფიქსირებული ფასით." },
        { num: "05", q: "მხოლოდ ქუთაისში მუშაობთ?", a: "არა — საქართველოს ნებისმიერი წერტილიდან ვმუშაობ. WhatsApp, Zoom და ელფოსტა — საკმარისია. ფიზიკურ შეხვედრებს ვაწყობ ქუთაისსა და თბილისში." },
        { num: "06", q: "ვმუშაობთ ხელშეკრულებით?", a: "დიახ — ყველა პროექტი ფორმდება მარტივი ხელშეკრულებით სადაც ჩაწერილია: რას ვაკეთებ, რა ვადაში, რა ფასი და რა გარანტიები. გადახდა ჩვეულებრივ ეტაპობრივად — 50% დაწყებამდე, 50% გაშვებამდე." },
      ],
    },
    about: {
      number: "06",
      kicker: "ჩემ შესახებ",
      photo: "ბესოს ფოტო",
      title: "გამარჯობა, მე ბესო ვარ",
      p1: "ვებ-დეველოპერი ვარ ქუთაისიდან და ვქმნი პრაქტიკულ, თანამედროვე ვებსაიტებს ქართული ბიზნესებისთვის — ძირითადად სასტუმროებისთვის, კოტეჯებისთვის და რესტორნებისთვის. ვმუშაობ უახლესი ხელსაწყოებით, ვპასუხობ სწრაფად და თითოეული პროექტი ჩემთვის მთავარი საქმეა.",
      p2: "კარგად ვიცნობ ადგილობრივ ტურიზმს, ამიტომ ვაკეთებ არა უბრალოდ „ლამაზ საიტებს“, არამედ ისეთებს, რომლებიც სტუმრისთვის გასაგებია და რეალურ შედეგზეა ორიენტირებული — მეტი შეტყობინება, მეტი ჯავშანი, მეტი ნდობა.",
      tags: ["Next.js", "მობილურზე მორგებული", "ქუთაისი", "სწრაფი მხარდაჭერა"],
    },
    contact: {
      number: "07",
      kicker: "მოდი ვისაუბროთ",
      pre: "მზად ხართ თქვენი ბიზნესის",
      em: "საიტისთვის?",
      sub: "უფასო კონსულტაცია — მომწერეთ და ერთად განვიხილავთ, რა სჭირდება თქვენს ბიზნესს ონლაინ.",
      btn: "WhatsApp-ით მოწერა",
    },
    footer: {
      tag: "ვებ-სტუდია · ქუთაისი",
      rights: "© 2026 Beso Surmava. ყველა უფლება დაცულია.",
    },
    loading: "იტვირთება",
    meta: {
      title: "ბესო სურმავა — ვებსაიტები ქართული ბიზნესებისთვის",
      description: "თანამედროვე, მობილურზე მორგებული ვებსაიტები სასტუმროებისთვის, კოტეჯებისთვის, რესტორნებისთვის და მცირე ბიზნესებისთვის. ცოცხალი ნამუშევრები, გამჭვირვალე ფასები, უფასო კონსულტაცია.",
      ogTitle: "ბესო სურმავა — ვებსაიტები ქართული ბიზნესებისთვის",
      ogDescription: "თანამედროვე ვებსაიტები სასტუმროებისთვის, კოტეჯებისთვის და რესტორნებისთვის — სუფთა დიზაინი, მობილური ვერსია, მეტი ჯავშანი.",
      ogAlt: "ბესო სურმავა — ვებ-სტუდია, ქუთაისი",
      twTitle: "ბესო სურმავა — ვებსაიტები ქართული ბიზნესებისთვის",
      twDescription: "პრემიუმ ვებსაიტები სასტუმროების, რესტორნებისა და ბრენდებისთვის — სწრაფი, მობილური, შედეგზე ორიენტირებული.",
    },
  },
  en: {
    navCta: "Get in touch",
    nav: [
      { label: "Home", href: "#top" },
      { label: "Services", href: "#services" },
      { label: "Work", href: "#work" },
      { label: "Pricing", href: "#pricing" },
      { label: "Contact", href: "#contact" },
    ],
    hero: {
      eyebrow: "Web Studio · Kutaisi / Tbilisi — Available",
      pre: "Websites that",
      em: "work",
      post: "for your business.",
      sub: "I build premium websites for hotels, restaurants and brands — clean, fast, mobile-first and built to drive real results.",
      cta1: "Start a project",
      cta2: "View work",
      scroll: "Scroll",
      stats: [
        { num: "3+", label: "Years" },
        { num: "12", label: "Projects" },
        { num: "24h", label: "Response" },
      ],
    },
    services: {
      number: "01",
      kicker: "What I do",
      title: "Full service — from idea to launch",
      intro: "Everything your business needs to succeed online, handled in one place.",
      items: [
        { num: "01", icon: "✦", title: "Web Design", body: "A modern, clean interface tailored to your brand — refined typography, warm colors and a considered grid.", tag: "Branding · Visual language" },
        { num: "02", icon: "↗", title: "Development", body: "Reliable, fast sites built with Next.js that keep running smoothly for years.", tag: "Next.js · Performance" },
        { num: "03", icon: "▢", title: "Mobile Version", body: "The phone screen comes first — most of your guests open the site on mobile.", tag: "Mobile-first" },
        { num: "04", icon: "✧", title: "SEO & Speed", body: "Visibility on Google and lightning-fast loads — Core Web Vitals 90+, AVIF images and clean meta tags.", tag: "Core Web Vitals · Schema" },
      ],
    },
    marquee: ["Hotels", "Restaurants", "Cottages", "Branding", "Websites", "Kutaisi"],
    work: {
      number: "02",
      kicker: "Work",
      title: "Selected projects",
      intro: "Live sites that are already up and serving real clients.",
      note: "A private project? I also build sites for restaurants, cottages and small brands —",
      noteLink: "get in touch",
      items: [
        { num: "01", name: "Georgian House", type: "Hotel · Kutaisi", desc: "A modern site with bookings and two languages." },
        { num: "02", name: "Kvirike Hills", type: "Boutique hotel · Cottages", desc: "A trilingual site with live bookings." },
      ],
    },
    process: {
      number: "03",
      kicker: "Process",
      title: "How I work",
      intro: "Simple, clear steps — all I need from you are photos and information.",
      steps: [
        { num: "01", title: "I learn about your business", body: "A short call by phone or WhatsApp: what you need, who your guests are and what the site should do." },
        { num: "02", title: "I send you a proposal", body: "Exact price, timeline and what you'll get — all upfront, with no surprises." },
        { num: "03", title: "You send photos and information", body: "Photos, prices, texts. If anything is missing, I'll help you prepare the structure and copy." },
        { num: "04", title: "I build and show you", body: "I send a link to a working version — you review it on phone and desktop, and we refine the details together." },
        { num: "05", title: "The site goes live", body: "I connect the domain, publish the site and hand everything over. Ongoing support if you want it." },
      ],
    },
    pricing: {
      number: "04",
      kicker: "Pricing",
      title: "Transparent packages",
      intro: "Final price depends on project scope — message me and get an exact proposal within a day.",
      popular: "Popular",
      from: "from",
      cta: "Get a proposal",
      note: "Domain and hosting are separate (roughly 40–100₾ per year) — I'll handle all of it for you.",
      tiers: [
        { name: "Landing page", price: "600₾", popular: false, desc: "A modern one-page site for a small business that needs an online presence fast.", features: ["One-page design", "Fully mobile-optimized", "Gallery and business description", "Contact: call, WhatsApp, map", "Ready in about 1 week"] },
        { name: "Standard site", price: "1000₾", popular: true, desc: "A full website for a hotel, cottage or restaurant — the most popular choice.", features: ["4–6 pages (rooms/menu, gallery…)", "Prices and detailed information", "Booking / contact form", "Two languages (Georgian + English)", "Basic SEO optimization", "Ready in about 2 weeks"] },
        { name: "Premium site", price: "1500₾", popular: false, desc: "Everything in Standard plus an admin panel — update prices and photos yourself, whenever you like.", features: ["Everything in Standard", "Admin panel for management", "Booking notifications by email", "More pages and features as needed", "Post-launch support"] },
      ],
    },
    faq: {
      number: "05",
      kicker: "FAQ",
      title: "What I'm often asked",
      items: [
        { num: "01", q: "How long does it take?", a: "Landing page — about 1 week. Standard site — 2 weeks. Premium package — 3–4 weeks, depending on complexity. The exact timeline is written into the proposal up-front." },
        { num: "02", q: "Can I update content myself?", a: "Yes — the Premium package includes an admin panel where you update prices, photos and copy yourself. For the Standard package, small changes are covered under my support." },
        { num: "03", q: "What do domain and hosting cost?", a: "Domain — about 40–60₾ per year. Hosting — usually free on Vercel (the popular choice) or 40–80₾ per year on premium options. I configure everything with you." },
        { num: "04", q: "What happens after launch?", a: "One month of free support — I fix any bugs at no cost. After that, either you update things yourself, or we agree on ongoing support at a fixed rate." },
        { num: "05", q: "Do you only work in Kutaisi?", a: "No — I work with clients anywhere in Georgia. WhatsApp, Zoom and email are enough. I take in-person meetings in Kutaisi and Tbilisi." },
        { num: "06", q: "Do we work with a contract?", a: "Yes — every project starts with a simple contract that spells out scope, timeline, price and guarantees. Payment is usually split — 50% to start, 50% at launch." },
      ],
    },
    about: {
      number: "06",
      kicker: "About me",
      photo: "Beso · photo",
      title: "Hi, I'm Beso",
      p1: "I'm a web developer from Kutaisi building practical, modern websites for Georgian businesses — mainly hotels, cottages and restaurants. I work with the latest tools, respond fast, and treat every project as my main job.",
      p2: "I know local tourism well, so I don't just make “pretty sites” — I make ones that are clear to guests and built for real results: more messages, more bookings, more trust.",
      tags: ["Next.js", "Mobile-first", "Kutaisi", "Fast support"],
    },
    contact: {
      number: "07",
      kicker: "Let's talk",
      pre: "Ready for your business",
      em: "website?",
      sub: "Free consultation — message me and we'll talk through what your business needs online.",
      btn: "Message on WhatsApp",
    },
    footer: {
      tag: "Web Studio · Kutaisi",
      rights: "© 2026 Beso Surmava. All rights reserved.",
    },
    loading: "Loading",
    meta: {
      title: "Beso Surmava — Websites for hospitality and small business",
      description: "Modern, mobile-first websites for hotels, cottages, restaurants and small businesses — based in Kutaisi, Georgia. Live work, transparent pricing, free consultation.",
      ogTitle: "Beso Surmava — Web studio, Kutaisi",
      ogDescription: "Premium websites for hotels, restaurants and brands — clean design, mobile-first, more bookings.",
      ogAlt: "Beso Surmava — Web studio, Kutaisi",
      twTitle: "Beso Surmava — Websites built for hospitality",
      twDescription: "Premium websites for hotels, restaurants and brands — fast, mobile-first, results-driven.",
    },
  },
} as const;

export type Copy = typeof copy.ka;
